#include "../structs/life.h"

inline const vector<parseLifeInstruction> LifeParams_V1 =
{
	{ LifeEnum::DO_MOVE, "DO_MOVE", { }, true},
	{ LifeEnum::ANIM_ONCE, "SET_ANIM_ONCE", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::ANIM_ALL_ONCE, "SET_ANIM_ALL_ONCE", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::SET_MODEL, "SET_MODEL", { { lifeExpr, varModel } }, true},
	{ LifeEnum::IF_EGAL, "IF_EGAL", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::IF_DIFFERENT, "IF_DIFFERENT", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::IF_SUP_EGAL, "IF_SUP_EGAL", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::IF_SUP, "IF_SUP", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::IF_INF_EGAL, "IF_INF_EGAL", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::IF_INF, "IF_INF", { { lifeExpr }, { lifeExpr }, { lifeGoto } }},
	{ LifeEnum::GOTO, "GOTO", { { lifeGoto } }},
	{ LifeEnum::RETURN, "RETURN", { }},
	{ LifeEnum::ENDLIFE, "ENDLIFE", { }},
	{ LifeEnum::SET_ANIM_REPEAT, "SET_ANIM_REPEAT", { { lifeConst } }, true},
	{ LifeEnum::SET_ANIM_MOVE, "SET_ANIM_MOVE", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::SET_TRACKMODE, "SET_TRACKMODE", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::HIT, "HIT", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeExpr }, { lifeConst } }, true},
	{ LifeEnum::MESSAGE, "MESSAGE", { { lifeConst } }},
	{ LifeEnum::MESSAGE_VALUE, "MESSAGE_VALUE", { }}, //NOT_USE
	{ LifeEnum::SET, "SET", { { lifeConst }, { lifeExpr } }},
	{ LifeEnum::INC, "INC", { { lifeConst } }},
	{ LifeEnum::DEC, "DEC", { { lifeConst } }},
	{ LifeEnum::ADD, "ADD", { { lifeConst }, { lifeExpr } }},
	{ LifeEnum::SUB, "SUB", { { lifeConst }, { lifeExpr } }},
	{ LifeEnum::SET_LIFE_MODE, "SET_LIFE_MODE", { { lifeConst } }, true},
	{ LifeEnum::SWITCH, "SWITCH", { { lifeExpr } }},
	{ LifeEnum::CASE, "CASE", { { lifeConst }, { lifeGoto } }},
	{ LifeEnum::CAMERA, "CAMERA", { }}, //Check camera number
	{ LifeEnum::START_CHRONO, "START_CHRONO", { }, true},
	{ LifeEnum::MULTI_CASE, "MULTI_CASE", {}}, //Custom parser
	{ LifeEnum::FOUND, "FOUND", { { lifeConst, varObject } }},
	{ LifeEnum::SET_LIFE, "SET_LIFE", { { lifeConst, varLifeScript } }, true},
	{ LifeEnum::DELETE_OBJ, "DELETE_OBJ", { { lifeConst, varObject } }},
	{ LifeEnum::TAKE, "TAKE", { { lifeConst } }},
	{ LifeEnum::SET_IN_HAND, "SET_IN_HAND", { { lifeConst, varObject } }},
	//{ LifeEnum::READ, "READ", { { lifeConst }, { lifeConst } }}, // !!! floppy version
	{ LifeEnum::READ, "READ_CD", { { lifeConst }, { lifeConst }, { lifeConst } }}, // !!! cd version
	{ LifeEnum::SET_ANIM_SOUND, "SET_ANIM_SOUND", { { lifeExpr }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::SPECIAL, "SPECIAL", { { lifeConst } }},
	{ LifeEnum::DO_REAL_ZV, "DO_REAL_ZV", { }, true},
	{ LifeEnum::SOUND, "SOUND", { { lifeExpr } }},
	{ LifeEnum::SET_FLAGS, "SET_FLAGS", { { lifeConst } }, true},
	{ LifeEnum::GAME_OVER, "GAME_OVER", { }},
	{ LifeEnum::MANUAL_ROT, "MANUAL_ROT", { }, true},
	{ LifeEnum::RND_FREQ, "RND_FREQ", { { lifeConst } }}, //Randomize sound frequency
	{ LifeEnum::SET_MUSIC, "SET_MUSIC", { { lifeConst } }},
	{ LifeEnum::SET_BETA, "SET_BETA", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::DO_ROT_ZV, "DO_ROT_ZV", { }, true},
	{ LifeEnum::CHANGE_ROOM, "CHANGE_ROOM", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::SET_INVENTORY_NAME, "SET_INVENTORY_NAME", { { lifeConst } }, true},
	{ LifeEnum::SET_INVENTORY_FLAG, "SET_INVENTORY_FLAG", { { lifeConst } }, true},
	{ LifeEnum::SET_INVENTORY_LIFE, "SET_INVENTORY_LIFE", { }, true},
	{ LifeEnum::SET_CAMERA_TARGET, "SET_CAMERA_TARGET", { { lifeConst, varObject } }},
	{ LifeEnum::DROP, "DROP", { { lifeExpr }, { lifeConst } }},
	{ LifeEnum::FIRE, "FIRE", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::TEST_COL, "TEST_COL", { { lifeConst } }, true},
	{ LifeEnum::SET_INVENTORY_MODEL, "SET_INVENTORY_MODEL", { { lifeConst } }, true},
	{ LifeEnum::SET_ALPHA, "SET_ALPHA", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::STOP_BETA, "STOP_BETA", { }},
	{ LifeEnum::DO_MAX_ZV, "DO_MAX_ZV", { }, true},
	{ LifeEnum::PUT, "PUT", { { lifeConst, varObject }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }},
	{ LifeEnum::SET_C, "SET_C", { { lifeConst }, { lifeExpr } }},
	{ LifeEnum::DO_NORMAL_ZV, "DO_NORMAL_ZV", { }},
	{ LifeEnum::DO_CARRE_ZV, "DO_CARRE_ZV", { }, true},
	{ LifeEnum::SOUND_THEN, "SOUND_THEN", { { lifeExpr }, { lifeExpr } }},
	{ LifeEnum::SET_LIGHT, "SET_LIGHT", { { lifeConst } }},
	{ LifeEnum::SET_SHAKING, "SET_SHAKING", { { lifeConst } }},
	{ LifeEnum::ALLOW_INVENTORY, "ALLOW_INVENTORY", { { lifeConst } }},
	{ LifeEnum::SET_OBJ_WEIGHT, "SET_OBJ_WEIGHT", { { lifeConst } }, true},
	{ LifeEnum::UP_COOR_Y, "UP_COOR_Y", { }},
	{ LifeEnum::SPEED, "SPEED", { }},
	{ LifeEnum::PUT_AT, "PUT_AT", { { lifeConst }, { lifeConst } }},
	{ LifeEnum::DEF_ZV, "DEF_ZV", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::HIT_OBJECT, "HIT_OBJECT", { { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::GET_HARD_CLIP, "GET_HARD_CLIP", { }},
	{ LifeEnum::SET_ANGLE, "SET_ANGLE", { { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::REP_SOUND, "REP_SOUND", { { lifeExpr }, { lifeConst } }},
	{ LifeEnum::THROW, "THROW", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true},
	{ LifeEnum::WATER, "WATER", { { lifeConst } }},
	{ LifeEnum::PICTURE, "PICTURE", { { lifeConst }, { lifeConst }, { lifeConst } }},
	{ LifeEnum::STOP_SOUND, "STOP_SOUND", { }},
	{ LifeEnum::NEXT_MUSIC, "NEXT_MUSIC", { { lifeConst } }},
	{ LifeEnum::FADE_MUSIC, "FADE_MUSIC", { { lifeConst } }},
	{ LifeEnum::STOP_HIT_OBJECT, "STOP_HIT_OBJECT", { }},
	{ LifeEnum::COPY_ANGLE, "COPY_ANGLE", { { lifeConst } }},
	{ LifeEnum::END_SEQUENCE, "END_SEQUENCE", { }}, //PREGZT hit by lamp
	{ LifeEnum::SOUND_THEN_REPEAT, "SOUND_THEN_REPEAT", { }},
	{ LifeEnum::WAIT_GAME_OVER, "WAIT_GAME_OVER", { }},
	{ LifeEnum::GET_MATRICE, "GET_MATRICE", { }},
	{ LifeEnum::STAGE_LIFE, "STAGE_LIFE", { { lifeConst } }},
	{ LifeEnum::CONTINUE_TRACK, "CONTINUE_TRACK", { }},
	{ LifeEnum::ANIM_RESET, "ANIM_RESET", { { lifeConst }, { lifeConst } }},
	{ LifeEnum::RESET_MOVE_MANUAL, "RESET_MOVE_MANUAL", { }},
	{ LifeEnum::PLUIE, "PLUIE", { }},
	{ LifeEnum::ANIM_HYBRIDE_ONCE, "ANIM_HYBRIDE_ONCE", { { lifeConst }, { lifeConst } }},
	{ LifeEnum::ANIM_HYBRIDE_REPEAT, "ANIM_HYBRIDE_REPEAT", { { lifeConst }, { lifeConst } }},
	{ LifeEnum::CALL_INVENTORY, "CALL_INVENTORY", { }},
	{ LifeEnum::BODY_RESET, "BODY_RESET", { { lifeExpr }, { lifeExpr } }},
	{ LifeEnum::DEL_INVENTORY, "DEL_INVENTORY", { }},
	{ LifeEnum::SET_INVENTORY, "SET_INVENTORY", { { lifeConst } }},
	{ LifeEnum::PLAY_SEQUENCE, "PLAY_SEQUENCE", { { lifeConst } }},
	{ LifeEnum::_2D_ANIM_SOUND, "_2D_ANIM_SOUND", { }},
	{ LifeEnum::SET_GROUND, "SET_GROUND", { { lifeConst } }},
	{ LifeEnum::PROTECT, "PROTECT", { }},
	{ LifeEnum::DEF_ABS_ZV, "DEF_ABS_ZV", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }, true },
	{ LifeEnum::DEF_SEQUENCE_SOUND, "DEF_SEQUENCE_SOUND", { { lifeConst } }},
	{ LifeEnum::READ_ON_PICTURE, "READ_ON_PICTURE", { { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst } }},
	{ LifeEnum::FIRE_UP_DOWN, "FIRE_UP_DOWN", { { lifeExpr }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeConst }, { lifeExpr } }},
	{ LifeEnum::DO_ROT_CLUT, "DO_ROT_CLUT", { { lifeConst }, { lifeConst }, { lifeConst } }, true },
	{ LifeEnum::STOP_CLUT, "STOP_CLUT", { }, true },
};

//floppy version of read
inline const parseLifeInstruction LifeParams_Floppy_V1 = 
	{ LifeEnum::READ, "READ", { { lifeConst }, { lifeConst } }};

// Start by 0
inline const vector<parseLifeExpr> LifeExprParams_V1 =
{
	{ EvalEnum::GET, "GET", { { lifeConst } }},
	{ EvalEnum::ACTOR_COLLIDER, "ACTOR_COLLIDER", { }, true, varObject },
	{ EvalEnum::TRIGGER_COLLIDER, "TRIGGER_COLLIDER", { }, true },
	{ EvalEnum::HARD_COLLIDER, "HARD_COLLIDER", { }, true },
	{ EvalEnum::HIT_TO, "HIT_TO", { }, true, varObject },
	{ EvalEnum::HIT_BY, "HIT_BY", { }, true, varObject },
	{ EvalEnum::ANIM, "ANIM", { }, true },
	{ EvalEnum::END_ANIM, "END_ANIM", { }, true },
	{ EvalEnum::FRAME, "FRAME", { }, true},
	{ EvalEnum::END_FRAME, "END_FRAME", { }},
	{ EvalEnum::MODEL, "MODEL", { }, true, varModel },
	{ EvalEnum::MARK, "MARK", { }, true },
	{ EvalEnum::NUM_TRACK, "NUM_TRACK", { }, true },
	{ EvalEnum::CHRONO, "CHRONO", { }, true },
	{ EvalEnum::ROOM_CHRONO, "ROOM_CHRONO", { }},
	{ EvalEnum::DIST, "DIST", { { lifeConst } }, true },
	{ EvalEnum::COL_BY, "COL_BY", { }, true, varObject },
	{ EvalEnum::IN_INVENTORY, "IN_INVENTORY", { { lifeExpr, varObject } }},
	{ EvalEnum::ACTION, "ACTION", { }},
	{ EvalEnum::POSREL, "POSREL", { { lifeConst } }, true },
	{ EvalEnum::KEYBOARD_INPUT, "KEYBOARD_INPUT", { }},
	{ EvalEnum::SPACE, "SPACE", { }},
	{ EvalEnum::CONTACT, "CONTACT", { }, true },
	{ EvalEnum::ALPHA, "ALPHA", { }, true },
	{ EvalEnum::BETA, "BETA", { }, true },
	{ EvalEnum::GAMMA, "GAMMA", { }, true },
	{ EvalEnum::IN_HAND, "IN_HAND", { }, varObject },
	{ EvalEnum::HIT_DAMAGE, "HIT_DAMAGE", { }, true},
	{ EvalEnum::CAMERA, "CAMERA", { }},
	{ EvalEnum::RAND, "RAND", { { lifeConst } }},
	{ EvalEnum::FALLING, "FALLING", { }, true},
	{ EvalEnum::ROOM, "ROOM", { }, true },
	{ EvalEnum::LIFE, "LIFE", { }, true, varLifeScript },
	{ EvalEnum::IS_FOUND, "IS_FOUND", { { lifeConst, varObject } }},
	{ EvalEnum::ROOMY, "ROOMY", { }, true },
	{ EvalEnum::TEST_ZV_END_ANIM, "TEST_ZV_END_ANIM", { { lifeConst }, { lifeConst } }, true},
	{ EvalEnum::MUSIC, "MUSIC", { }},
	{ EvalEnum::GET_C, "GET_C", { { lifeConst } }},
	{ EvalEnum::STAGE, "STAGE", { }, true },
	{ EvalEnum::THROWING, "THROWING", { { lifeConst, varObject } }}
};
