#include "life_structs.h"

inline const vector<parseLifeInstruction> LifeTable_v1 =
{
  { LifeEnum::DO_MOVE, {} },
  { LifeEnum::ANIM_ONCE, { lifeConst, lifeConst }, true },
  { LifeEnum::ANIM_ALL_ONCE, { lifeConst, lifeConst }, true },
  { LifeEnum::BODY, {} },
  { LifeEnum::IF_EGAL, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::IF_DIFFERENT, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::IF_SUP_EGAL, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::IF_SUP, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::IF_INF_EGAL, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::IF_INF, { lifeExpr, lifeExpr, lifeGoto }, true },
  { LifeEnum::GOTO, { lifeGoto }, true },
  { LifeEnum::RETURN, {} },
  { LifeEnum::ENDLIFE, {}, true },
  { LifeEnum::ANIM_REPEAT, {} },
  { LifeEnum::ANIM_MOVE, {} },
  { LifeEnum::TRACKMODE, {} },
  { LifeEnum::HIT, {} },
  { LifeEnum::MESSAGE, { lifeConst }, true },
  { LifeEnum::MESSAGE_VALUE, {} },
  { LifeEnum::VAR, { lifeConst, lifeExpr }, true },
  { LifeEnum::INC, { lifeConst }, true },
  { LifeEnum::DEC, { lifeConst }, true },
  { LifeEnum::ADD, {} },
  { LifeEnum::SUB, {} },
  { LifeEnum::LIFE_MODE, {} },
  { LifeEnum::SWITCH, { lifeExpr }, true },
  { LifeEnum::CASE, {  lifeConst, lifeGoto }, true },
  { LifeEnum::CAMERA, {} },
  { LifeEnum::START_CHRONO, {} },
  { LifeEnum::MULTI_CASE, {}, true }, //Custom parser
  { LifeEnum::FOUND, { lifeConst }, true },
  { LifeEnum::LIFE, { lifeConst }, true },
  { LifeEnum::DELETE, { lifeConst }, true },
  { LifeEnum::TAKE, {} },
  { LifeEnum::IN_HAND, { lifeConst }, true },
  { LifeEnum::READ, {} },
  { LifeEnum::ANIM_SOUND, {} },
  { LifeEnum::SPECIAL, {} },
  { LifeEnum::DO_REAL_ZV, {} },
  { LifeEnum::SOUND, { lifeExpr }, true },
  { LifeEnum::FLAGS, { lifeConst }, true },
  { LifeEnum::GAME_OVER, {} },
  { LifeEnum::MANUAL_ROT, {} },
  { LifeEnum::RND_FREQ, {} },
  { LifeEnum::MUSIC, {} },
  { LifeEnum::SET_BETA, {  lifeConst, lifeConst  }, true },
  { LifeEnum::DO_ROT_ZV, {}, true },
  { LifeEnum::CHANGEROOM, {} },
  { LifeEnum::FOUND_NAME, { lifeConst }, true  },
  { LifeEnum::FOUND_FLAG, {} },
  { LifeEnum::FOUND_LIFE, {} },
  { LifeEnum::CAMERA_TARGET, {} },
  { LifeEnum::DROP, {} },
  { LifeEnum::FIRE, {} },
  { LifeEnum::TEST_COL, {} },
  { LifeEnum::FOUND_BODY, {} },
  { LifeEnum::SET_ALPHA, {  lifeConst, lifeConst  }, true },
  { LifeEnum::STOP_BETA, {} },
  { LifeEnum::DO_MAX_ZV, {} },
  { LifeEnum::PUT, {} },
  { LifeEnum::C_VAR, {} },
  { LifeEnum::DO_NORMAL_ZV, {} },
  { LifeEnum::DO_CARRE_ZV, {} },
  { LifeEnum::SOUND_THEN, {} },
  { LifeEnum::LIGHT, {} },
  { LifeEnum::SHAKING, {} },
  { LifeEnum::ALLOW_INVENTORY, {} },
  { LifeEnum::FOUND_WEIGHT, {} },
  { LifeEnum::UP_COOR_Y, {} },
  { LifeEnum::SPEED, {} },
  { LifeEnum::PUT_AT, {} },
  { LifeEnum::DEF_ZV, {} },
  { LifeEnum::HIT_OBJECT, {  lifeConst, lifeConst  }, true },
  { LifeEnum::GET_HARD_CLIP, {} },
  { LifeEnum::ANGLE, {} },
  { LifeEnum::REP_SOUND, {} },
  { LifeEnum::THROW, {} },
  { LifeEnum::WATER, {} },
  { LifeEnum::PICTURE, {} },
  { LifeEnum::STOP_SOUND, {} },
  { LifeEnum::NEXT_MUSIC, {} },
  { LifeEnum::FADE_MUSIC, {} },
  { LifeEnum::STOP_HIT_OBJECT, {} },
  { LifeEnum::COPY_ANGLE, {} },
  { LifeEnum::END_SEQUENCE, {} },
  { LifeEnum::SOUND_THEN_REPEAT, {} },
  { LifeEnum::WAIT_GAME_OVER, {} },
  { LifeEnum::GET_MATRICE, {} },
  { LifeEnum::STAGE_LIFE, {} },
  { LifeEnum::CONTINUE_TRACK, {} },
  { LifeEnum::ANIM_RESET, {} },
  { LifeEnum::RESET_MOVE_MANUAL, {} },
  { LifeEnum::PLUIE, {} },
  { LifeEnum::ANIM_HYBRIDE_ONCE, {  lifeConst, lifeConst }, true },
  { LifeEnum::ANIM_HYBRIDE_REPEAT, {  lifeConst, lifeConst  }, true },
  { LifeEnum::CALL_INVENTORY, {} },
  { LifeEnum::BODY_RESET, {} },
  { LifeEnum::DEL_INVENTORY, {} },
  { LifeEnum::SET_INVENTORY, {} },
  { LifeEnum::PLAY_SEQUENCE, {} },
  { LifeEnum::_2D_ANIM_SOUND, {} },
  { LifeEnum::SET_GROUND, {} },
  { LifeEnum::PROTECT, {} },
  { LifeEnum::DEF_ABS_ZV, {} },
  { LifeEnum::DEF_SEQUENCE_SOUND, {} },
  { LifeEnum::READ_ON_PICTURE, {} },
  { LifeEnum::FIRE_UP_DOWN, {} },
  { LifeEnum::DO_ROT_CLUT, {} },
  { LifeEnum::STOP_CLUT, {} }
};

// Start by -1
inline const vector<parseLifeFunction> ExprTable_v1 =
{
  { EvalEnum::VAR, { lifeConst }, true },
  { EvalEnum::ACTOR_COLLIDER, {} },
  { EvalEnum::TRIGGER_COLLIDER, {}, true },
  { EvalEnum::HARD_COLLIDER, {}, true },
  { EvalEnum::HIT, {} },
  { EvalEnum::HIT_BY, {} },
  { EvalEnum::ANIM, {}, true },
  { EvalEnum::END_ANIM, {}, true },
  { EvalEnum::FRAME, {} },
  { EvalEnum::END_FRAME, {} },
  { EvalEnum::BODY, {} },
  { EvalEnum::MARK, {} },
  { EvalEnum::NUM_TRACK, {} },
  { EvalEnum::CHRONO, {} },
  { EvalEnum::ROOM_CHRONO, {} },
  { EvalEnum::DIST, {} },
  { EvalEnum::COL_BY, { } },
  { EvalEnum::ISFOUND, {} },
  { EvalEnum::ACTION, {} },
  { EvalEnum::POSREL, { lifeConst }, true },
  { EvalEnum::KEYBOARD_INPUT, {} },
  { EvalEnum::SPACE, {} },
  { EvalEnum::CONTACT, {} },
  { EvalEnum::ALPHA, {} },
  { EvalEnum::BETA, {} },
  { EvalEnum::GAMMA, {} },
  { EvalEnum::INHAND, {} },
  { EvalEnum::HITFORCE, {} },
  { EvalEnum::CAMERA, {} },
  { EvalEnum::RAND, {} },
  { EvalEnum::FALLING, {} },
  { EvalEnum::ROOM, {} },
  { EvalEnum::LIFE, {} },
  { EvalEnum::OBJECT, { lifeConst }, true  },
  { EvalEnum::ROOMY, {} },
  { EvalEnum::TEST_ZV_END_ANIM, {} },
  { EvalEnum::MUSIC, {} },
  { EvalEnum::C_VAR, {} },
  { EvalEnum::STAGE, {} },
  { EvalEnum::THROW, { lifeConst }, true }
};