#include "life_structs.h"

inline const vector<parseLifeInstruction> LifeTable_v1 =
{
	{ LifeEnum::DO_MOVE, "DO_MOVE", { }},
	{ LifeEnum::ANIM_ONCE, "ANIM_ONCE", { lifeConst, lifeConst }},
	{ LifeEnum::ANIM_ALL_ONCE, "ANIM_ALL_ONCE", { lifeConst, lifeConst }},
	{ LifeEnum::BODY, "BODY", { lifeExpr }},
	{ LifeEnum::IF_EGAL, "IF_EGAL", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::IF_DIFFERENT, "IF_DIFFERENT", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::IF_SUP_EGAL, "IF_SUP_EGAL", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::IF_SUP, "IF_SUP", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::IF_INF_EGAL, "IF_INF_EGAL", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::IF_INF, "IF_INF", { lifeExpr, lifeExpr, lifeGoto }},
	{ LifeEnum::GOTO, "GOTO", { lifeGoto }},
	{ LifeEnum::RETURN, "RETURN", { }},
	{ LifeEnum::ENDLIFE, "ENDLIFE", { }},
	{ LifeEnum::ANIM_REPEAT, "ANIM_REPEAT", { lifeConst }},
	{ LifeEnum::ANIM_MOVE, "ANIM_MOVE", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::TRACKMODE, "TRACKMODE", { lifeConst, lifeConst }},
	{ LifeEnum::HIT, "HIT", { lifeConst, lifeConst, lifeConst, lifeConst, lifeExpr, lifeConst }},
	{ LifeEnum::MESSAGE, "MESSAGE", { lifeConst }},
	{ LifeEnum::MESSAGE_VALUE, "MESSAGE_VALUE", { }},
	{ LifeEnum::VAR, "VAR", { lifeConst, lifeExpr }},
	{ LifeEnum::INC, "INC", { lifeConst }},
	{ LifeEnum::DEC, "DEC", { lifeConst }},
	{ LifeEnum::ADD, "ADD", { lifeConst, lifeExpr }},
	{ LifeEnum::SUB, "SUB", { lifeConst, lifeExpr }},
	{ LifeEnum::LIFE_MODE, "LIFE_MODE", { lifeConst }},
	{ LifeEnum::SWITCH, "SWITCH", { lifeExpr }},
	{ LifeEnum::CASE, "CASE", { lifeConst, lifeGoto }},
	{ LifeEnum::CAMERA, "CAMERA", { }},
	{ LifeEnum::START_CHRONO, "START_CHRONO", { }},
	{ LifeEnum::MULTI_CASE, "MULTI_CASE", {}}, //Custom parser
	{ LifeEnum::FOUND, "FOUND", { lifeConst }},
	{ LifeEnum::LIFE, "LIFE", { lifeConst }},
	{ LifeEnum::DELETE, "DELETE", { lifeConst }},
	{ LifeEnum::TAKE, "TAKE", { lifeConst }},
	{ LifeEnum::IN_HAND, "IN_HAND", { lifeConst }},
	{ LifeEnum::READ, "READ", { lifeConst, lifeConst }}, //3rd lifeConst in cd version
	{ LifeEnum::ANIM_SOUND, "ANIM_SOUND", { lifeExpr, lifeConst, lifeConst }},
	{ LifeEnum::SPECIAL, "SPECIAL", { lifeConst }},
	{ LifeEnum::DO_REAL_ZV, "DO_REAL_ZV", { }},
	{ LifeEnum::SOUND, "SOUND", { lifeExpr }},
	{ LifeEnum::FLAGS, "FLAGS", { lifeConst }},
	{ LifeEnum::GAME_OVER, "GAME_OVER", { }},
	{ LifeEnum::MANUAL_ROT, "MANUAL_ROT", { }},
	{ LifeEnum::RND_FREQ, "RND_FREQ", { lifeConst }},
	{ LifeEnum::MUSIC, "MUSIC", { lifeConst }},
	{ LifeEnum::SET_BETA, "SET_BETA", { lifeConst, lifeConst }},
	{ LifeEnum::DO_ROT_ZV, "DO_ROT_ZV", { }},
	{ LifeEnum::CHANGEROOM, "CHANGEROOM", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::FOUND_NAME, "FOUND_NAME", { lifeConst }},
	{ LifeEnum::FOUND_FLAG, "FOUND_FLAG", { lifeConst }},
	{ LifeEnum::FOUND_LIFE, "FOUND_LIFE", { }},
	{ LifeEnum::CAMERA_TARGET, "CAMERA_TARGET", { lifeConst }},
	{ LifeEnum::DROP, "DROP", { lifeExpr, lifeConst }},
	{ LifeEnum::FIRE, "FIRE", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::TEST_COL, "TEST_COL", { lifeConst }},
	{ LifeEnum::FOUND_BODY, "FOUND_BODY", { lifeConst }},
	{ LifeEnum::SET_ALPHA, "SET_ALPHA", { lifeConst, lifeConst }},
	{ LifeEnum::STOP_BETA, "STOP_BETA", { }},
	{ LifeEnum::DO_MAX_ZV, "DO_MAX_ZV", { }},
	{ LifeEnum::PUT, "PUT", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::C_VAR, "C_VAR", { lifeConst, lifeExpr }},
	{ LifeEnum::DO_NORMAL_ZV, "DO_NORMAL_ZV", { }},
	{ LifeEnum::DO_CARRE_ZV, "DO_CARRE_ZV", { }},
	{ LifeEnum::SOUND_THEN, "SOUND_THEN", { lifeExpr, lifeExpr }},
	{ LifeEnum::LIGHT, "LIGHT", { lifeConst }},
	{ LifeEnum::SHAKING, "SHAKING", { lifeConst }},
	{ LifeEnum::ALLOW_INVENTORY, "ALLOW_INVENTORY", { lifeConst }},
	{ LifeEnum::FOUND_WEIGHT, "FOUND_WEIGHT", { lifeConst }},
	{ LifeEnum::UP_COOR_Y, "UP_COOR_Y", { }},
	{ LifeEnum::SPEED, "SPEED", { }},
	{ LifeEnum::PUT_AT, "PUT_AT", { lifeConst, lifeConst }},
	{ LifeEnum::DEF_ZV, "DEF_ZV", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::HIT_OBJECT, "HIT_OBJECT", { lifeConst, lifeConst }},
	{ LifeEnum::GET_HARD_CLIP, "GET_HARD_CLIP", { }},
	{ LifeEnum::ANGLE, "ANGLE", { lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::REP_SOUND, "REP_SOUND", { lifeExpr, lifeConst }},
	{ LifeEnum::THROW, "THROW", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::WATER, "WATER", { lifeConst }},
	{ LifeEnum::PICTURE, "PICTURE", { lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::STOP_SOUND, "STOP_SOUND", { }},
	{ LifeEnum::NEXT_MUSIC, "NEXT_MUSIC", { lifeConst }},
	{ LifeEnum::FADE_MUSIC, "FADE_MUSIC", { lifeConst }},
	{ LifeEnum::STOP_HIT_OBJECT, "STOP_HIT_OBJECT", { }},
	{ LifeEnum::COPY_ANGLE, "COPY_ANGLE", { lifeConst }},
	{ LifeEnum::END_SEQUENCE, "END_SEQUENCE", { }},
	{ LifeEnum::SOUND_THEN_REPEAT, "SOUND_THEN_REPEAT", { }},
	{ LifeEnum::WAIT_GAME_OVER, "WAIT_GAME_OVER", { }},
	{ LifeEnum::GET_MATRICE, "GET_MATRICE", { }},
	{ LifeEnum::STAGE_LIFE, "STAGE_LIFE", { lifeConst }},
	{ LifeEnum::CONTINUE_TRACK, "CONTINUE_TRACK", { }},
	{ LifeEnum::ANIM_RESET, "ANIM_RESET", { lifeConst, lifeConst }},
	{ LifeEnum::RESET_MOVE_MANUAL, "RESET_MOVE_MANUAL", { }},
	{ LifeEnum::PLUIE, "PLUIE", { }},
	{ LifeEnum::ANIM_HYBRIDE_ONCE, "ANIM_HYBRIDE_ONCE", { lifeConst, lifeConst }},
	{ LifeEnum::ANIM_HYBRIDE_REPEAT, "ANIM_HYBRIDE_REPEAT", { lifeConst, lifeConst }},
	{ LifeEnum::CALL_INVENTORY, "CALL_INVENTORY", { }},
	{ LifeEnum::BODY_RESET, "BODY_RESET", { lifeExpr, lifeExpr }},
	{ LifeEnum::DEL_INVENTORY, "DEL_INVENTORY", { }},
	{ LifeEnum::SET_INVENTORY, "SET_INVENTORY", { lifeConst }},
	{ LifeEnum::PLAY_SEQUENCE, "PLAY_SEQUENCE", { lifeConst }},
	{ LifeEnum::_2D_ANIM_SOUND, "_2D_ANIM_SOUND", { }},
	{ LifeEnum::SET_GROUND, "SET_GROUND", { lifeConst }},
	{ LifeEnum::PROTECT, "PROTECT", { }},
	{ LifeEnum::DEF_ABS_ZV, "DEF_ABS_ZV", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::DEF_SEQUENCE_SOUND, "DEF_SEQUENCE_SOUND", { lifeConst }},
	{ LifeEnum::READ_ON_PICTURE, "READ_ON_PICTURE", { lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::FIRE_UP_DOWN, "FIRE_UP_DOWN", { lifeExpr, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeConst, lifeExpr }},
	{ LifeEnum::DO_ROT_CLUT, "DO_ROT_CLUT", { lifeConst, lifeConst, lifeConst }},
	{ LifeEnum::STOP_CLUT, "STOP_CLUT", { }},
};

// Start by 0
inline const vector<parseLifeExpr> ExprTable_v1 =
{
	{ EvalEnum::VAR, "VAR", { lifeConst }},
	{ EvalEnum::ACTOR_COLLIDER, "ACTOR_COLLIDER", { }},
	{ EvalEnum::TRIGGER_COLLIDER, "TRIGGER_COLLIDER", { }},
	{ EvalEnum::HARD_COLLIDER, "HARD_COLLIDER", { }},
	{ EvalEnum::HIT, "HIT", { }},
	{ EvalEnum::HIT_BY, "HIT_BY", { }},
	{ EvalEnum::ANIM, "ANIM", { }},
	{ EvalEnum::END_ANIM, "END_ANIM", { }},
	{ EvalEnum::FRAME, "FRAME", { }},
	{ EvalEnum::END_FRAME, "END_FRAME", { }},
	{ EvalEnum::BODY, "BODY", { }},
	{ EvalEnum::MARK, "MARK", { }},
	{ EvalEnum::NUM_TRACK, "NUM_TRACK", { }},
	{ EvalEnum::CHRONO, "CHRONO", { }},
	{ EvalEnum::ROOM_CHRONO, "ROOM_CHRONO", { }},
	{ EvalEnum::DIST, "DIST", { lifeConst }},
	{ EvalEnum::COL_BY, "COL_BY", { }},
	{ EvalEnum::ISFOUND, "ISFOUND", { lifeExpr }},
	{ EvalEnum::ACTION, "ACTION", { }},
	{ EvalEnum::POSREL, "POSREL", { lifeConst }},
	{ EvalEnum::KEYBOARD_INPUT, "KEYBOARD_INPUT", { }},
	{ EvalEnum::SPACE, "SPACE", { }},
	{ EvalEnum::CONTACT, "CONTACT", { }},
	{ EvalEnum::ALPHA, "ALPHA", { }},
	{ EvalEnum::BETA, "BETA", { }},
	{ EvalEnum::GAMMA, "GAMMA", { }},
	{ EvalEnum::INHAND, "INHAND", { }},
	{ EvalEnum::HITFORCE, "HITFORCE", { }},
	{ EvalEnum::CAMERA, "CAMERA", { }},
	{ EvalEnum::RAND, "RAND", { lifeConst }},
	{ EvalEnum::FALLING, "FALLING", { }},
	{ EvalEnum::ROOM, "ROOM", { }},
	{ EvalEnum::LIFE, "LIFE", { }},
	{ EvalEnum::OBJECT, "OBJECT", { lifeConst }},
	{ EvalEnum::ROOMY, "ROOMY", { }},
	{ EvalEnum::TEST_ZV_END_ANIM, "TEST_ZV_END_ANIM", { lifeConst, lifeConst }},
	{ EvalEnum::MUSIC, "MUSIC", { }},
	{ EvalEnum::C_VAR, "C_VAR", { lifeConst }},
	{ EvalEnum::STAGE, "STAGE", { }},
	{ EvalEnum::THROW, "THROW", { lifeConst }}
};
