#pragma once
#include <vector>
#include <string>
#include "../world/world.h"
#include "../resources/resources.h"
#include "../../common/raylib_cpp.hpp"

using namespace std;
namespace openAITD {

	class BaseRenderer {
	public:
		World* world;
		Resources* resources;
		Camera mainCamera = {
			{ 0.0f, 0, -5 },
			{ 0.0f, 0.0f, 0.0f },
			{ 0.0f, 1.0f, 0.0f },   // mainCamera up vector (rotation towards target)
			60.,
			CAMERA_PERSPECTIVE
		};
		int curStageId = -1;
		int curCameraId = -1;
		WCamera* curCamera = 0;
		Matrix perspective;

		const int getScreenW() { return resources->config.screenW; }
		const int getScreenH() { return resources->config.screenH; }

		BaseRenderer(World* world) {
			this->world = world;
			this->resources = world->resources;
		}

		~BaseRenderer() {
			clearCamera();
		}

		virtual void loadCamera(int newCameraId)
		{
			printf("Load Camera %d\n", newCameraId);
			curCameraId = newCameraId;
			curCamera = &resources->stages[world->curStageId].cameras[newCameraId];
			auto& camPers = curCamera->pers;
			perspective = MatrixPerspective(camPers.yfov, camPers.aspectRatio, camPers.znear, camPers.zfar);

			mainCamera.position = curCamera->position;
			mainCamera.target = Vector3Add(curCamera->position, Vector3Negate(Vector3RotateByQuaternion({ 0,0,1 }, curCamera->rotation)));
			mainCamera.up = Vector3RotateByQuaternion({ 0,1,0 }, curCamera->rotation);
		}

		void clearCamera()
		{
			if (curCameraId == -1) return;
			curCameraId = -1;
			curCamera = 0;
		}

		Vector3 GetWorldToScreenZ(Vector3 position) {
			const int& width = getScreenW();
			const int& height = getScreenH();
			auto& matProj = perspective;
			Matrix matView = MatrixLookAt(mainCamera.position, mainCamera.target, mainCamera.up);
			Vector3 depth = Vector3Transform(position, matView);
			Quaternion worldPos = { position.x, position.y, position.z, 1.0f };
			worldPos = QuaternionTransform(worldPos, matView);
			worldPos = QuaternionTransform(worldPos, matProj);
			Vector3 ndcPos = { worldPos.x / worldPos.w, -worldPos.y / worldPos.w, worldPos.z / worldPos.w };
			Vector3 screenPosition = { (ndcPos.x + 1.0f) / 2.0f * (float)width, (ndcPos.y + 1.0f) / 2.0f * (float)height, -depth.z };
			return screenPosition;
		}

		void DrawBounds(Bounds bb, Color color)
		{
			Vector3 vecs[8];
			// Front face        
			vecs[0] = { bb.min.x, bb.max.y, bb.max.z }; // Top left
			vecs[1] = { bb.max.x, bb.max.y, bb.max.z }; // Top right
			vecs[2] = { bb.min.x, bb.min.y, bb.max.z }; // Bottom left
			vecs[3] = { bb.max.x, bb.min.y, bb.max.z }; // Bottom right
			// Back face
			vecs[4] = { bb.min.x, bb.max.y, bb.min.z }; // Top left
			vecs[5] = { bb.max.x, bb.max.y, bb.min.z }; // Top right
			vecs[6] = { bb.min.x, bb.min.y, bb.min.z }; // Bottom left
			vecs[7] = { bb.max.x, bb.min.y, bb.min.z }; // Bottom right

			DrawLine3D(vecs[0], vecs[1], color);
			DrawLine3D(vecs[1], vecs[3], color);
			DrawLine3D(vecs[3], vecs[2], color);
			DrawLine3D(vecs[2], vecs[0], color);

			DrawLine3D(vecs[4], vecs[5], color);
			DrawLine3D(vecs[5], vecs[7], color);
			DrawLine3D(vecs[7], vecs[6], color);
			DrawLine3D(vecs[6], vecs[4], color);

			DrawLine3D(vecs[0], vecs[4], color);
			DrawLine3D(vecs[1], vecs[5], color);
			DrawLine3D(vecs[2], vecs[6], color);
			DrawLine3D(vecs[3], vecs[7], color);
		}

		void processSkin(GameObject& gobj, Model& model)
		{
			if (!model.skin || gobj.animation.id == -1) return;

			if (gobj.animation.curPose) {
				model.ApplyPose(gobj.animation.curPose);
				model.UpdateBuffer();
			}
		}

		void renderObject(GameObject& gobj, Color tint)
		{
			auto rmodel = resources->models.getModel(gobj.modelId, world->altModels);
			auto& model = rmodel->model;

			/*
			const Matrix matTranslation = MatrixTranslate(pos.x, pos.y, pos.z);
			Matrix matTransform = MatrixMultiply(gobj.getRotMatrix(), matTranslation);
			
			matTransform = MatrixMultiply(matTransform, Metrics::roomMatrix);
			matTransform = MatrixMultiply(matTransform, MatrixTranslate(roomPos.x,roomPos.y,roomPos.z));
			*/
			const Vector3 pos = gobj.getPosition();
  		const Vector3 roomPos = world->curStage->rooms[gobj.getRoomId()].origPosition;

			Matrix matr = MatrixIdentity();
			matr = MatrixMultiply(MatrixTranslate(roomPos.x, roomPos.y, roomPos.z), matr);
			matr = MatrixMultiply(MatrixTranslate(pos.x, pos.y, pos.z), matr);
			matr = MatrixMultiply(gobj.getRotMatrix(), matr);
			matr = MatrixMultiply(MatrixRotateY(PI), matr);
			
			// Combine model transformation matrix (model.transform) with matrix generated by function parameters (matTransform)
			auto m = rlGetMatrixModelview();
			rlSetMatrixModelview(MatrixMultiply(matr, m));
			model.Render();
			rlSetMatrixModelview(m);
		}

	};

}
